// Mock data for development and testing

import {
  Listing,
  PropertyListing,
  VehicleListing,
  ListingCategory,
  PropertyType,
  VehicleType,
} from "@rent360/types";

export const mockPropertyListings: PropertyListing[] = [
  {
    id: "prop-1",
    title: "Modern 3BR Apartment in East Legon",
    description:
      "Beautiful modern apartment with stunning views. Fully furnished with high-speed internet, AC, and 24/7 security.",
    category: ListingCategory.PROPERTY,
    propertyType: PropertyType.APARTMENT,
    ownerId: "user-1",
    images: [
      "https://via.placeholder.com/800x600?text=Property+1",
      "https://via.placeholder.com/800x600?text=Property+1-2",
    ],
    price: 2500,
    currency: "GHS",
    location: {
      address: "East Legon",
      city: "Accra",
      country: "Ghana",
      latitude: 5.6498,
      longitude: -0.1574,
    },
    amenities: ["WiFi", "AC", "Parking", "Security", "Pool"],
    bedrooms: 3,
    bathrooms: 2,
    squareMeters: 120,
    furnished: true,
    availability: true,
    rating: 4.8,
    reviewCount: 24,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "prop-2",
    title: "Cozy 2BR House in Cantonments",
    description:
      "Charming house in quiet neighborhood. Perfect for families or professionals.",
    category: ListingCategory.PROPERTY,
    propertyType: PropertyType.HOUSE,
    ownerId: "user-2",
    images: ["https://via.placeholder.com/800x600?text=Property+2"],
    price: 3000,
    currency: "GHS",
    location: {
      address: "Cantonments",
      city: "Accra",
      country: "Ghana",
      latitude: 5.5892,
      longitude: -0.1748,
    },
    amenities: ["WiFi", "AC", "Garden", "Security"],
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 95,
    furnished: true,
    availability: true,
    rating: 4.6,
    reviewCount: 18,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-11-28"),
  },
  {
    id: "prop-3",
    title: "Luxury 4BR Villa with Pool",
    description:
      "Exclusive villa with private pool and gym. Perfect for executives.",
    category: ListingCategory.PROPERTY,
    propertyType: PropertyType.HOUSE,
    ownerId: "user-3",
    images: ["https://via.placeholder.com/800x600?text=Property+3"],
    price: 5000,
    currency: "GHS",
    location: {
      address: "Airport Residential",
      city: "Accra",
      country: "Ghana",
      latitude: 5.6037,
      longitude: -0.1870,
    },
    amenities: ["WiFi", "AC", "Pool", "Gym", "Security", "Generator"],
    bedrooms: 4,
    bathrooms: 3,
    squareMeters: 200,
    furnished: true,
    availability: true,
    rating: 4.9,
    reviewCount: 31,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-12-03"),
  },
];

export const mockVehicleListings: VehicleListing[] = [
  {
    id: "veh-1",
    title: "Toyota Camry 2022 - Automatic",
    description:
      "Well-maintained Toyota Camry with leather interior and GPS navigation.",
    category: ListingCategory.VEHICLE,
    vehicleType: VehicleType.CAR,
    ownerId: "user-4",
    images: ["https://via.placeholder.com/800x600?text=Vehicle+1"],
    price: 150,
    currency: "GHS",
    location: {
      address: "Osu",
      city: "Accra",
      country: "Ghana",
      latitude: 5.5600,
      longitude: -0.1817,
    },
    make: "Toyota",
    model: "Camry",
    year: 2022,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    hasGPS: true,
    availability: true,
    rating: 4.7,
    reviewCount: 15,
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-12-02"),
  },
  {
    id: "veh-2",
    title: "Honda CR-V 2023 - SUV",
    description: "Spacious SUV perfect for families. Includes child seats.",
    category: ListingCategory.VEHICLE,
    vehicleType: VehicleType.CAR,
    ownerId: "user-5",
    images: ["https://via.placeholder.com/800x600?text=Vehicle+2"],
    price: 200,
    currency: "GHS",
    location: {
      address: "East Legon",
      city: "Accra",
      country: "Ghana",
      latitude: 5.6498,
      longitude: -0.1574,
    },
    make: "Honda",
    model: "CR-V",
    year: 2023,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 7,
    hasGPS: true,
    availability: true,
    rating: 4.8,
    reviewCount: 22,
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-12-04"),
  },
];

export const mockCategories = [
  {
    id: "properties",
    name: "Properties",
    description: "Apartments, houses, commercial spaces",
    count: 5000,
    icon: "home",
  },
  {
    id: "vehicles",
    name: "Vehicles",
    description: "Cars, motorbikes, trucks",
    count: 2500,
    icon: "car",
  },
  {
    id: "equipment",
    name: "Equipment",
    description: "Heavy machinery, tools",
    count: 1200,
    icon: "wrench",
  },
  {
    id: "events",
    name: "Events",
    description: "Tents, chairs, sound systems",
    count: 800,
    icon: "calendar",
  },
];

export const mockLocations = [
  { city: "Accra", country: "Ghana", count: 3200 },
  { city: "Lagos", country: "Nigeria", count: 2800 },
  { city: "Nairobi", country: "Kenya", count: 2100 },
  { city: "Cape Town", country: "South Africa", count: 1900 },
  { city: "Kampala", country: "Uganda", count: 1500 },
];
